# Generated by Django 5.2.8 on 2025-12-05 23:59

import django.db.models.deletion
from django.db import migrations, models
import mptt.fields

def rebuild_tree(apps, schema_editor):
    from ..models import InventoryItemGroup

    if hasattr(InventoryItemGroup, '_tree_manager'):
        InventoryItemGroup._tree_manager.rebuild()



class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory', '0015_alter_asset_storage_location'),
        ('users', '0015_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitemgroup',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner'),
        ),
        migrations.RunPython(rebuild_tree, migrations.RunPython.noop),
    ]
